# Generated by Django 4.0.2 on 2022-02-23 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toDoApp', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
